name: "Build & test .NET solution"

on:
  workflow_call:

jobs:

  build-dotnet-job:
    name: "Build .NET solution"
    runs-on: ubuntu-latest
    steps:

      - name: "Clone Git repository"
        uses: actions/checkout@v3

      - name: ".NET Build"
        run: dotnet build "./src/cs" --nologo --verbosity minimal --configuration Release

  test-dotnet-job:
    name: "Test .NET solution"
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Windows x64, os: windows-latest }
        - { name: Linux x64, os: ubuntu-latest }
        - { name: macOS x64, os: macos-latest }
    defaults:
      run:
        shell: bash
    steps:

    - name: "Clone Git repository"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: "Install Clang: Windows"
      if: matrix.platform.os == 'windows-latest'
      run: |
        source "${{ github.workspace }}\.github\scripts\install-clang-x64-windows.sh"
  
    - name: "Install Clang: Linux"
      if: matrix.platform.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install gcc-i686-linux-gnu gcc-x86-64-linux-gnu gcc-aarch64-linux-gnu llvm-14 clang-14

    - name: "Test .NET solution"
      run: |
        dotnet test ${{ github.workspace }}/src/cs --nologo --verbosity minimal --configuration Release

    - name: "Snipe test files"
      uses: actions/upload-artifact@v3
      with:
        name: "Test Data ${{ matrix.platform.name }}"
        path: |
          ${{ github.workspace }}/src/cs/tests/*Tests*/**/*.json

