name: "Main"

on:
  workflow_dispatch:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:

  build-test-job:
    name: "Build & teat"
    uses: "./.github/workflows/build-test.yml"
